<?php

defined('ABSPATH') || exit;

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group([
        'key' => 'group_59089a20ba7d8',
        'title' => 'Configurator',
        'fields' => [
            [
                'key' => 'field_59089dd8d3865',
                'label' => 'Общий код',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_5908a002e1847',
                'label' => 'Код HEAD для всех страниц',
                'name' => 'head_code',
                'type' => 'textarea',
                'value' => null,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 15,
                'new_lines' => '',
            ],
            [
                'key' => 'field_5908a072e1848',
                'label' => 'Код FOOTER для всех страниц',
                'name' => 'footer_code',
                'type' => 'textarea',
                'value' => null,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 15,
                'new_lines' => '',
            ],
            [
                'key' => 'field_5933b50d3ebb5',
                'label' => 'Формы',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_593406b27e390',
                'label' => 'Настройка форм',
                'name' => 'email_profile',
                'type' => 'repeater',
                'value' => null,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => [
                    [
                        'key' => 'field_593408bb65d7e',
                        'label' => 'Отбор',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_593437c01afba',
                        'label' => 'Форма',
                        'name' => 'form',
                        'type' => 'radio',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [
                            'default' => 'Все формы',
                        ],
                        'allow_null' => 0,
                        'other_choice' => 1,
                        'save_other_choice' => 0,
                        'default_value' => 'default',
                        'layout' => 'vertical',
                        'return_format' => 'value',
                    ],
                    [
                        'key' => 'field_593408c665d7f',
                        'label' => 'Параметры отправки',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_593406fb7e391',
                        'label' => 'Email получателя',
                        'name' => 'email',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'можно несколько через запятую',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5934076d7e392',
                        'label' => 'Тема письма',
                        'name' => 'subject',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Новое сообщение с сайта %site%',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5934077e7e393',
                        'label' => 'Текст письма',
                        'name' => 'message',
                        'type' => 'textarea',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Данные формы:
%fields%',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'br',
                    ],
                    [
                        'key' => 'field_593409615f453',
                        'label' => 'Имя отправителя',
                        'name' => 'from',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59343c0f18dbc',
                        'label' => 'Адрес для ответа',
                        'name' => 'addreply',
                        'type' => 'email',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_593409945f454',
                        'label' => 'Копия письма (CC)',
                        'name' => 'cc',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_593409c15f455',
                        'label' => 'Скрытая копия (BCC)',
                        'name' => 'bcc',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_593433366bd96',
                        'label' => 'Отправка через SMTP',
                        'name' => 'smtp',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_593433bff5877',
                        'label' => 'Сервер SMTP',
                        'name' => 'host',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_593433366bd96',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'smtp.yandex.ru',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_593433eaf5878',
                        'label' => 'Пользователь',
                        'name' => 'username',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_593433366bd96',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59343458f5879',
                        'label' => 'Пароль',
                        'name' => 'password',
                        'type' => 'password',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_593433366bd96',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ],
                    [
                        'key' => 'field_5934347ef587a',
                        'label' => 'Авторизация',
                        'name' => 'auth',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_593433366bd96',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 1,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_59343491f587b',
                        'label' => 'Тип защиты',
                        'name' => 'secure',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_593433366bd96',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'ssl',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_593434a8f587c',
                        'label' => 'Порт',
                        'name' => 'port',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_593433366bd96',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 465,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_593434b2f587d',
                        'label' => 'Кодировка',
                        'name' => 'charset',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_593433366bd96',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'utf-8',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59340dfd68e13',
                        'label' => 'Поведение формы',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_59340e7668e14',
                        'label' => 'Прятать форму после отправки',
                        'name' => 'hide',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_593412ebc534b',
                        'label' => 'Прятать лайтбокс после отправки',
                        'name' => 'hide_lbox',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_5934130ec534c',
                        'label' => 'Класс для лайтбокса',
                        'name' => 'lbox_class',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'классы лайтбоксов через запятую, пример: lbox1,lbox2',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_593412ebc534b',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'lbox',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59340ebd68e15',
                        'label' => 'Задержка до исчезновения',
                        'name' => 'delay',
                        'type' => 'number',
                        'value' => null,
                        'instructions' => 'задержка исчезновения сообщения в миллисекундах<br>(0 - не скрывать)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 3000,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ],
                    [
                        'key' => 'field_59340f1168e16',
                        'label' => 'Перенаправление на страницу',
                        'name' => 'redirect',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59340e7668e15',
                        'label' => 'Перенаправлять в новом окне',
                        'name' => 'redirect_new_tab',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_59340fc4b1930',
                        'label' => 'Сообщение об успешной отправке',
                        'name' => 'success_msg',
                        'type' => 'textarea',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Ваше сообщение отправлено!
Спасибо за обращение.',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => 'br',
                    ],
                    [
                        'key' => 'field_59341000b1931',
                        'label' => 'Сообщение об ошибке',
                        'name' => 'error_msg',
                        'type' => 'textarea',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Ошибка отправки!
Попробуйте позже.',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => 'br',
                    ],
                    [
                        'key' => 'field_59341037b1932',
                        'label' => 'Сообщение во время отправки',
                        'name' => 'wait_msg',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Идет отправка...',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59340a3b5f458',
                        'label' => 'Ответ отправителю',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_59340ccbbd521',
                        'label' => 'Включить ответ отправителю',
                        'name' => 'reply',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_59340a7b5f459',
                        'label' => 'Название поля',
                        'name' => 'reply_email',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'поле, в котором указан адрес для ответа',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Email',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59340ace5f45a',
                        'label' => 'Тема письма',
                        'name' => 'reply_subject',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59340b075f45b',
                        'label' => 'Текcт письма',
                        'name' => 'reply_message',
                        'type' => 'textarea',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'br',
                    ],
                    [
                        'key' => 'field_59340b215f45c',
                        'label' => 'Файл для отпавки',
                        'name' => 'reply_file',
                        'type' => 'file',
                        'value' => null,
                        'instructions' => 'файл, который будет отправлен',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'array',
                        'library' => 'all',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ],
                    [
                        'key' => 'field_59340b828a625',
                        'label' => 'Экспорт CSV',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_59340c89bd520',
                        'label' => 'Включить экспорт в CSV',
                        'name' => 'export',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_59340bb08a626',
                        'label' => 'Имя файла',
                        'name' => 'export_file',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'имя файла для экспорта в CSV',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59340bcd8a627',
                        'label' => 'Список полей',
                        'name' => 'export_fields',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'список полей для экспорта (через запятую)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59340b828a6251',
                        'label' => 'reCAPTCHA',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_59340c89bd5201',
                        'label' => 'Включить reCAPTCHA',
                        'name' => 'recaptcha',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_59340bb08a6261',
                        'label' => 'Ключ сайта',
                        'name' => 'recaptcha_site_key',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_59340bb08a6262',
                        'label' => 'Секретный ключ',
                        'name' => 'recaptcha_secret_key',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                ],
            ],
            [
                'key' => 'field_59089e09d3866',
                'label' => 'Типы записей',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_5908acb4a4828',
                'label' => 'Произвольные типы записей',
                'name' => 'custom_post_types',
                'type' => 'repeater',
                'value' => null,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'collapsed' => 'field_5908b95fa482b',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => [
                    [
                        'key' => 'field_5908bf7bc54ab',
                        'label' => 'Название',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_5908b795a4829',
                        'label' => 'Имя типа записи',
                        'name' => 'name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'Имя необходимо указать строчными латинскими символами без пробелов.<br>
Можно использовать нижнее подчеркивание.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5908bf21a9877',
                        'label' => 'Настройки',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_5908b832a482a',
                        'label' => 'Название во множественном числе',
                        'name' => 'many_name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5908b95fa482b',
                        'label' => 'Название в единственном числе',
                        'name' => 'single_name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5908b97fa482c',
                        'label' => 'Название пункта меню',
                        'name' => 'menu_name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5908b9aca482d',
                        'label' => 'Иконка в меню',
                        'name' => 'icon',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'Иконку можно выбрать по адресу: <a href="https://developer.wordpress.org/resource/dashicons/" target="_blank">https://developer.wordpress.org/resource/dashicons/</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5908ba9f09ad0',
                        'label' => 'Элементы управления',
                        'name' => 'support',
                        'type' => 'checkbox',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [
                            'title' => 'Заголовок',
                            'editor' => 'Текстовый редактор',
                            'thumbnail' => 'Миниатюра записи',
                            'excerpt' => 'Цитата',
                            'author' => 'Автор',
                            'revisions' => 'Редакции',
                            'comments' => 'Комментарии',
                            'trackbacks' => 'Обратные ссылки',
                            'post-formats' => 'Форматы постов',
                        ],
                        'allow_custom' => 0,
                        'save_custom' => 0,
                        'default_value' => [
                            0 => 'title',
                            1 => 'editor',
                            2 => 'thumbnail',
                        ],
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value',
                    ],
                    [
                        'key' => 'field_5908bc6509ad1',
                        'label' => 'Ярлык для типа записи',
                        'name' => 'slug',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'По умолчанию: название типа записи.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5909ca1edc65da1',
                        'label' => 'Показывать в REST',
                        'name' => 'show_in_rest',
                        'type' => 'true_false',
                        'value' => true,
                        'instructions' => 'Выводить тип записи в REST API',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'default_value' => 1,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_5909ca1edc65da',
                        'label' => 'Публичный адрес',
                        'name' => 'publicly_queryable',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => 'Наличие публичного url для таксономии',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'default_value' => 1,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                ],
            ],
            [
                'key' => 'field_59089e1ad3867',
                'label' => 'Таксономии',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_5909ca1edc654',
                'label' => 'Произвольные таксономии',
                'name' => 'custom_taxonomies',
                'type' => 'repeater',
                'value' => null,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'collapsed' => 'field_5908b95fa482b',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => [
                    [
                        'key' => 'field_5909ca1edc655',
                        'label' => 'Название',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_5909ca1edc656',
                        'label' => 'Имя таксономии',
                        'name' => 'name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'Имя необходимо указать строчными латинскими символами без пробелов.<br>
Можно использовать нижнее подчеркивание.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5909ca1edc657',
                        'label' => 'Настройки',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_5909ca1edc65b',
                        'label' => 'Тип таксономии',
                        'name' => 'type',
                        'type' => 'select',
                        'value' => null,
                        'instructions' => 'Иерархический - как категории<br>
Плоский - как теги',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [
                            'true' => 'Иерархический',
                            'false' => 'Плоский',
                        ],
                        'default_value' => [],
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_5909ca1edc65c',
                        'label' => 'Типы записей',
                        'name' => 'post_type_select',
                        'type' => 'select',
                        'value' => null,
                        'instructions' => 'Типы записей, к которым будет привязана данная таксономия.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [],
                        'default_value' => [],
                        'allow_null' => 0,
                        'multiple' => 1,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_5909ca1edc658',
                        'label' => 'Название во множественном числе',
                        'name' => 'many_name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5909ca1edc659',
                        'label' => 'Название в единственном числе',
                        'name' => 'single_name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5909ca1edc65a',
                        'label' => 'Название пункта меню',
                        'name' => 'menu_name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5909ca1edc65d',
                        'label' => 'Ярлык для таксономии',
                        'name' => 'slug',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => 'По умолчанию: название типа записи.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5909ca1edc65da',
                        'label' => 'Публичный адрес',
                        'name' => 'publicly_queryable',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => 'Наличие публичного url для таксономии',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'default_value' => 1,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                ],
            ],
            [
                'key' => 'field_59089e34d3869',
                'label' => 'Отбор записей',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_5909d59a8ecc0',
                'label' => 'Отбор записей по параметрам',
                'name' => 'custom_query',
                'type' => 'repeater',
                'value' => null,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => [
                    [
                        'key' => 'field_5909d86163b10',
                        'label' => 'Название',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_5909d84663b0f',
                        'label' => 'Название отбора',
                        'name' => 'name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5909d86f63b11',
                        'label' => 'Параметры',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_5909d6568ecc1',
                        'label' => 'Тип записи',
                        'name' => 'post_type_select',
                        'type' => 'select',
                        'value' => null,
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [],
                        'default_value' => [],
                        'allow_null' => 0,
                        'multiple' => 1,
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_5909d7188ecc3',
                        'label' => 'Количество записей на страницу',
                        'name' => 'posts_per_page',
                        'type' => 'number',
                        'value' => null,
                        'instructions' => 'Если оставить пустым, то будут выведены все записи.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ],
                    [
                        'key' => 'field_5909d7488ecc4',
                        'label' => 'Поддержка постраничной навигации',
                        'name' => 'paged',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_5909d959b93de',
                        'label' => 'Таксономии',
                        'name' => 'taxonomy',
                        'type' => 'repeater',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => [
                            [
                                'key' => 'field_5909d978b93df',
                                'label' => 'Таксономия',
                                'name' => 'taxonomy_for_query',
                                'type' => 'select',
                                'value' => null,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [],
                                'default_value' => [],
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ],
                            [
                                'key' => 'field_5909d995b93e0',
                                'label' => 'Значение',
                                'name' => 'terms',
                                'type' => 'text',
                                'value' => null,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                        ],
                    ],
                    [
                        'key' => 'field_59b87c297d892',
                        'label' => 'Произвольные поля',
                        'name' => 'meta_query',
                        'type' => 'repeater',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'collapsed' => 'field_59b87c5d7d893',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => [
                            [
                                'key' => 'field_59b87c5d7d893',
                                'label' => 'Название поля',
                                'name' => 'key',
                                'type' => 'text',
                                'value' => null,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                            [
                                'key' => 'field_59b87f587d895',
                                'label' => 'Условие',
                                'name' => 'compare',
                                'type' => 'select',
                                'value' => null,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    '=' => '=',
                                    '!=' => '!=',
                                    '>' => '>',
                                    '>=' => '>=',
                                    '<' => '<',
                                    '<=' => '<=',
                                    'LIKE' => 'LIKE',
                                    'NOT LIKE' => 'NOT LIKE',
                                    'IN' => 'IN',
                                    'NOT IN' => 'NOT IN',
                                    'BETWEEN' => 'BETWEEN',
                                    'NOT BETWEEN' => 'NOT BETWEEN',
                                    'EXISTS' => 'EXISTS',
                                    'NOT EXISTS' => 'NOT EXISTS',
                                    'REGEXP' => 'REGEXP',
                                    'NOT REGEXP' => 'NOT REGEXP',
                                ],
                                'default_value' => [
                                    0 => '=',
                                ],
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ],
                            [
                                'key' => 'field_59b87f497d894',
                                'label' => 'Значение поля',
                                'name' => 'value',
                                'type' => 'text',
                                'value' => null,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                            [
                                'key' => 'field_59b87f7c7d896',
                                'label' => 'Тип',
                                'name' => 'type',
                                'type' => 'select',
                                'value' => null,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'NUMERIC' => 'NUMERIC',
                                    'DECIMAL' => 'DECIMAL',
                                    'SIGNED' => 'SIGNED',
                                    'UNSIGNED' => 'UNSIGNED',
                                    'CHAR' => 'CHAR',
                                    'BINARY' => 'BINARY',
                                    'DATETIME' => 'DATETIME',
                                    'DATE' => 'DATE',
                                    'TIME' => 'TIME',
                                ],
                                'default_value' => [
                                    0 => 'CHAR',
                                ],
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ],
                        ],
                    ],
                    [
                        'key' => 'field_59b8854747af1',
                        'label' => 'Режим сравнения по полям',
                        'name' => 'meta_relation',
                        'type' => 'radio',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [
                            'AND' => 'И',
                            'OR' => 'ИЛИ',
                        ],
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => 'AND',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ],
                ],
            ],
            [
                'key' => 'field_5910b0a008c0c',
                'label' => 'Отбор термов',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_5910b06808c02',
                'label' => 'Отбор термов по параметрам',
                'name' => 'custom_term_query',
                'type' => 'repeater',
                'value' => null,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => [
                    [
                        'key' => 'field_5910b06808c03',
                        'label' => 'Название',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_5910b06808c04',
                        'label' => 'Название отбора',
                        'name' => 'name',
                        'type' => 'text',
                        'value' => null,
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5910b06808c05',
                        'label' => 'Параметры',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_5910b06808c06',
                        'label' => 'Таксономия',
                        'name' => 'taxonomy_select',
                        'type' => 'select',
                        'value' => null,
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [],
                        'default_value' => [],
                        'allow_null' => 0,
                        'multiple' => 1,
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_5910b06808c08',
                        'label' => 'Скрывать термины без записей',
                        'name' => 'hide_empty',
                        'type' => 'true_false',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 1,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_5910b20608c0d',
                        'label' => 'Сортировка',
                        'name' => 'orderby',
                        'type' => 'select',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [
                            'name' => 'Название',
                            'count' => 'Количество записей',
                            'slug' => 'Slug',
                            'id' => 'ID',
                        ],
                        'default_value' => [
                            0 => 'name',
                        ],
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_5910b2de08c0e',
                        'label' => 'Порядок сортировки',
                        'name' => 'order',
                        'type' => 'select',
                        'value' => null,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [
                            'ASC' => 'По возрастанию',
                            'DESC' => 'По убыванию',
                        ],
                        'default_value' => [
                            0 => 'ASC',
                        ],
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ],
                ],
            ],
            [
                'key' => 'field_5910b0a008c0b',
                'label' => 'Информация',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_5b6a912d38d5c',
                'label' => 'Информация о сайте',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => 'Версия PHP: <b>' . phpversion() . '</b><br><br>' .
                    'Расширение CURL: <b>' . (extension_loaded('curl') ? 'Установлено' : ' Не установлено') . '</b><br><br>' .
                    'Расширение ZIP: <b>' . (extension_loaded('zip') ? 'Установлено' : ' Не установлено') . '</b><br><br>' .
                    'Папка темы: <b>' . '<input type="text" style="width:90%;" value="' . get_bloginfo('template_url') . '">' . '</b><br><br>' .
                    '<a href="' . get_site_url() . '/?action=import_data" class="button">Загрузить данные</a>&nbsp;&nbsp;<a href="' . get_site_url() . '/?action=import_images" class="button">Загрузить медиафайлы</a><br><br>' . wtw_info_message(),
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'config',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ]);

endif;

function wtw_info_message()
{
    $message = '';
    if (isset($_GET['status'])) {
        if ($_GET['status'] === 'uploaded_data') {
            $message = 'Данные загружены.';
        } elseif ($_GET['status'] === 'uploaded_media') {
            $message = 'Медиафайлы загружены.';
        }
    }
    return '<b>' . $message . '</b>';
}
